import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Nav from '../components/Nav/Nav'
import About from '../components/About/About'
import Skills from '../components/Skills/Skills'
import Projects from '../components/Projects/Projects'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Carolyn Portfolio</title>

        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Aboreto&display=swap" />
      </Head>

      <main>
        <header></header>

        <div className={styles.scrollable}>
          <div className={styles.introContainer}></div>
          <h2 className={styles.main}>
            Hi! I&apos;m Carolyn <p>A software Engineer </p>
            <p>based in Atlanta</p>
          </h2>
          <div className={styles.second}>
            <About></About>
          </div>
          <section className={styles.third}>
            <Skills></Skills>
          </section>
          <div className={styles.projectContainerthrid}>
            <div className={styles.projectContainer}>
              <h1>PROJECTS </h1>
            </div>
            <Projects />
          </div>

          {/* <div className={styles.introContainertwo}>jdjdjddd</div>
          <div className={styles.introContainer}>jddodo</div> */}
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}
